### ISSUE TITLE
🚀 CI/CDテスト自動実行の設定

### ISSUE THREAD

**Issue by jun-kb** [jun-kb/engineer_journey#41]
## 概要
GitHub ActionsにVitestテストの自動実行を組み込み、PRやpush時にテストが自動で実行される環境を構築します。

## 現状
- PR制御ボットワークフローは存在（`.github/workflows/pr_control.yaml`）
- テスト環境（vitest）は構築済み
- CI/CDでのテスト自動実行が未設定

### 1. テスト実行ワークフロー（`.github/workflows/test.yaml`）
```yaml
name: 🧪 Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test
      
    - name: Run build check
      run: npm run build
```

### 2. PR制御ボットとの統合
既存の `pr_control.yaml` にテスト成功を前提条件として追加を検討

## 期待される効果
- ✅ コード品質の自動保証
- ✅ リグレッション検出の自動化
- ✅ ビルドエラーの早期発見
- ✅ 開発者の手動テスト実行忘れ防止
- ✅ mainブランチの品質維持

## 実装タスク
- [ ] `.github/workflows/test.yaml` ワークフロー作成
- [ ] Node.jsバージョン確認（package.jsonのengines設定確認）
- [ ] テストワークフロー動作確認
- [ ] PR作成時のテスト自動実行確認
- [ ] mainブランチpush時のテスト自動実行確認
- [ ] （オプション）テスト失敗時のPR制御ボット連携検討

## 拡張機能候補
- **カバレッジレポート**: テスト結果とカバレッジの自動計測
- **テスト結果通知**: Slack等への通知機能
- **パフォーマンステスト**: ビルド時間・テスト実行時間の監視

## Priority
High - コード品質とデプロイ安全性の向上に直結

## 関連Issue
- #40 (テストカバレッジレポート設定) - カバレッジ機能実装後に連携可能
