### ISSUE TITLE
⚡ GitHub Actions パフォーマンス最適化

### ISSUE THREAD

**Issue by jun-kb** [jun-kb/engineer_journey#52]
## 概要
現在のGitHub Actions設定を最適化し、CI/CDパイプラインの実行速度と効率を向上させる。

## 現在の状況
- Node.js 18、npm キャッシュ使用
- テスト、カバレッジ、ビルドを順次実行
- Asia/Tokyoタイムゾーン設定済み

### 1. 依存関係キャッシュ戦略の強化
```yaml
- name: Cache node modules
  uses: actions/cache@v4
  with:
    path: ~/.npm
    key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
    restore-keys: |
      ${{ runner.os }}-node-
```

### 2. ジョブの並列化
```yaml
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20]  # 複数Node.jsバージョンでのテスト
    steps:
      # テスト実行
      
  coverage:
    runs-on: ubuntu-latest
    steps:
      # カバレッジ専用ジョブ
      
  build:
    runs-on: ubuntu-latest
    needs: [test]  # テスト成功後に実行
    steps:
      # ビルド実行
```

### 3. 高速化オプションの活用
```yaml
- name: Install dependencies with faster options
  run: npm ci --prefer-offline --no-audit --progress=false

- name: Run tests with coverage (optimized)
  run: npm run test:coverage -- --run --reporter=verbose
  env:
    NODE_OPTIONS: '--max-old-space-size=4096'
```

### 4. 条件付き実行の追加
```yaml
- name: Run build only for main branch
  if: github.ref == 'refs/heads/main'
  run: npm run build

- name: Skip tests if only docs changed
  if: steps.changed-files.outputs.only_changed \!= 'true' || contains(steps.changed-files.outputs.all_changed_files, '.md')
  run: echo "Skipping tests - only documentation changed"
```

### 5. 失敗時の詳細レポート
```yaml
- name: Upload test results
  if: failure()
  uses: actions/upload-artifact@v4
  with:
    name: test-results
    path: |
      coverage/
      test-results.xml
```

## 実装箇所
- `.github/workflows/test.yaml` - ワークフロー最適化
- `package.json` - 高速化オプション追加（任意）

## 期待される効果
- CI実行時間の短縮（目標: 30%削減）
- 並列処理による効率化
- リソース使用量の最適化
- 失敗時のデバッグ効率向上

## 優先度
低（現在も正常動作するが、開発効率向上のため）

## 参考情報
- 現在の平均実行時間: 約2-3分
- 目標実行時間: 約1-2分
- 使用ランナー: ubuntu-latest
